# Site settings
title: "Puzzor"
email: puzzorsj@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "https://puzzor.github.io/"
title_description: "A blog by @Puzzor"
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: ""
github_repository: https://github.com/Puzzor
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: puzzor
github_username:  puzzor
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/puzzorsj\">Puzzor</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/Puzzor\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

theme: jekyll-theme-hacker